Fix one compiling error with g++ 10.2.1
The error is following.

TestTrafficForwarder.cpp: In member function 'virtual void
TrafficForwarder_addVlanTag_Test::TestBody()':
TestTrafficForwarder.cpp:47:35: error: cast from 'unsigned char*' to
'tpacket_auxdata*' increases required alignment of target type
[-Werror=cast-align]
   47 |     struct tpacket_auxdata* aux = (struct
      tpacket_auxdata*)CMSG_DATA(cmsg);
            |                                   ^

Now add one void* conversion to avoid it.